// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PI_ES2_Grupo8.Models;

namespace PI_ES2_Grupo8.Migrations
{
    [DbContext(typeof(ServicoDomicilioDbContext))]
    [Migration("20181116084252_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PI_ES2_Grupo8.Models.Enfermeiros", b =>
                {
                    b.Property<int>("EnfermeirosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Especializacao")
                        .IsRequired();

                    b.Property<string>("Morada")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.HasKey("EnfermeirosId");

                    b.ToTable("Enfermeiros");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.HorarioServicoDomicilio", b =>
                {
                    b.Property<int>("HorarioServicoDomicilioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Data");

                    b.Property<int?>("EnfermeirosId");

                    b.Property<int>("Hora");

                    b.HasKey("HorarioServicoDomicilioId");

                    b.HasIndex("EnfermeirosId");

                    b.ToTable("HorarioServicoDomicilio");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MaterialId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.Medico", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Morada")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.HasKey("MedicoId");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.Receita", b =>
                {
                    b.Property<int>("ReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MedicoId");

                    b.Property<int>("UtenteId");

                    b.Property<DateTime>("date");

                    b.HasKey("ReceitaId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.ReceitarTratamento", b =>
                {
                    b.Property<int>("ReceitaId");

                    b.Property<int>("TratamentoId");

                    b.Property<int>("ReceitarTratamentoId");

                    b.HasKey("ReceitaId", "TratamentoId");

                    b.HasIndex("TratamentoId");

                    b.ToTable("ReceitarTratamento");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.Tratamento", b =>
                {
                    b.Property<int>("TratamentoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HorarioServicoDomicilioId");

                    b.Property<string>("TipodeTratamento")
                        .IsRequired();

                    b.HasKey("TratamentoId");

                    b.HasIndex("HorarioServicoDomicilioId");

                    b.ToTable("Tratamento");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.Utente", b =>
                {
                    b.Property<int>("UtenteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int?>("HorarioServicoDomicilioId");

                    b.Property<string>("Morada")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.HasKey("UtenteId");

                    b.HasIndex("HorarioServicoDomicilioId");

                    b.ToTable("Utente");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.HorarioServicoDomicilio", b =>
                {
                    b.HasOne("PI_ES2_Grupo8.Models.Enfermeiros", "Enfermeiros")
                        .WithMany()
                        .HasForeignKey("EnfermeirosId");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.Receita", b =>
                {
                    b.HasOne("PI_ES2_Grupo8.Models.Medico", "medico")
                        .WithMany("receitas")
                        .HasForeignKey("MedicoId");

                    b.HasOne("PI_ES2_Grupo8.Models.Utente", "utente")
                        .WithMany("receitas")
                        .HasForeignKey("UtenteId");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.ReceitarTratamento", b =>
                {
                    b.HasOne("PI_ES2_Grupo8.Models.Receita", "receita")
                        .WithMany("receitarTratamentos")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PI_ES2_Grupo8.Models.Tratamento", "tratamento")
                        .WithMany("receitarTratamentos")
                        .HasForeignKey("TratamentoId");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.Tratamento", b =>
                {
                    b.HasOne("PI_ES2_Grupo8.Models.HorarioServicoDomicilio")
                        .WithMany("Tratamentos")
                        .HasForeignKey("HorarioServicoDomicilioId");
                });

            modelBuilder.Entity("PI_ES2_Grupo8.Models.Utente", b =>
                {
                    b.HasOne("PI_ES2_Grupo8.Models.HorarioServicoDomicilio")
                        .WithMany("Utente")
                        .HasForeignKey("HorarioServicoDomicilioId");
                });
#pragma warning restore 612, 618
        }
    }
}
